/////// Todo Actions

export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS"
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS"
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS"

export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS"

///// Category Actions

export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"

///// SWITCH THEME

export const SWITCH_THEME = "SWITCH_THEME"